### ISSUE TITLE
Icon for <Link />

### ISSUE THREAD

**Issue by arianacofone** [arianadziedzic/bullet_journal#2]
I'm trying to create a menu that is designated by png icons. Every time I use a link they render properly in the screen, but when I try to access them in a folder in my doc it doesn't work.

Here's the code -

In Component
<Link to="/dashboard" id="snooze-icon" />

In CSS
# snooze-icon {

  background-image: url(./../img/clock.png);
}

Blarg!

**Comment by ddruker** [comment]
Include the image files and add a class to give the elements some width and height.
